[package]
name = "termd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "termd"
path = "src/main.rs"

[lib]
name = "termd"
path = "src/lib.rs"

[dependencies]
tonic = { version = "0.14", features = ["transport"] }
prost = "0.14"
prost-types = "0.14"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync", "net"] }
tower = "0.5"
clap = { version = "4", features = ["derive"] }
nix = { version = "0.31", features = ["process", "signal", "term"] }
libc = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
uuid = { version = "1", features = ["v4"] }
anyhow = "1"
hostname = "0.4"
libghostty-vt = { git = "https://github.com/jamessanford/libghostty-rs", rev = "0bc60291aeaaca618fbd86edd17510c3d42dcab0", default-features = false, features = ["kitty-graphics"] }
libghostty-vt-sys = { git = "https://github.com/jamessanford/libghostty-rs", rev = "0bc60291aeaaca618fbd86edd17510c3d42dcab0", default-features = false, features = ["pkg-config", "kitty-graphics"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tonic-prost = "0.14.6"

[build-dependencies]
tonic-prost-build = "0.14"
pkg-config = "0.3"

[dev-dependencies]
tempfile = "3"
